services:
  - type: web
    name: gps-bus-rio
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: IN_DOCKER
        value: "1"
      - key: PERF_LOG_ENABLED
        value: "0"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: GUNICORN_THREADS
        value: "2"
      - key: GUNICORN_TIMEOUT
        value: "180"